import { useParams } from "wouter";
import { trpc } from "@/lib/trpc";
import { Streamdown } from "streamdown";
import { Button } from "@/components/ui/button";
import { Sparkles, Download, FileText } from "lucide-react";

export default function PublicShare() {
  const params = useParams<{ slug: string }>();
  const slug = params.slug ?? "";
  const { data, isLoading, error } = trpc.share.publicGet.useQuery({ slug }, { enabled: !!slug, retry: false });

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ background: "oklch(0.05 0.01 265)" }}>
        <div className="text-white">Loading…</div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="min-h-screen flex items-center justify-center text-white" style={{ background: "oklch(0.05 0.01 265)" }}>
        <div className="text-center">
          <h1 className="text-2xl mb-2">Link not available</h1>
          <p style={{ color: "oklch(0.55 0.02 265)" }}>This share link may have been revoked or has expired.</p>
        </div>
      </div>
    );
  }

  const { project, report } = data;

  return (
    <div className="min-h-screen text-white" style={{ background: "oklch(0.05 0.01 265)" }}>
      <header className="border-b px-6 py-4 flex items-center justify-between" style={{ borderColor: "oklch(0.18 0.05 265 / 0.5)", background: "oklch(0.07 0.02 265 / 0.6)", backdropFilter: "blur(12px)" }}>
        <div className="flex items-center gap-2">
          <Sparkles className="w-5 h-5" style={{ color: "oklch(0.65 0.30 280)" }} />
          <span className="font-light tracking-wider">Collective Soul: Oracle</span>
        </div>
        {report && (
          <div className="flex gap-2">
            <a href={`/api/public/share/${slug}/report.pdf`} target="_blank" rel="noreferrer">
              <Button variant="ghost" size="sm"><Download className="w-4 h-4 mr-1.5" /> PDF</Button>
            </a>
            <a href={`/api/public/share/${slug}/report.pptx`} target="_blank" rel="noreferrer">
              <Button variant="ghost" size="sm"><FileText className="w-4 h-4 mr-1.5" /> PPTX</Button>
            </a>
          </div>
        )}
      </header>

      <main className="max-w-4xl mx-auto px-6 py-10">
        {project && (
          <div className="mb-10">
            <p className="text-xs uppercase tracking-widest mb-2" style={{ color: "oklch(0.55 0.02 265)" }}>Prediction project</p>
            <h1 className="text-4xl font-light mb-3">{project.title}</h1>
            {project.topic && <p className="text-lg" style={{ color: "oklch(0.75 0.02 265)" }}>{project.topic}</p>}
            {project.description && <p className="text-sm mt-3" style={{ color: "oklch(0.65 0.02 265)" }}>{project.description}</p>}
          </div>
        )}

        {report ? (
          <article className="prose prose-invert max-w-none" style={{ color: "oklch(0.85 0.02 265)" }}>
            {report.title && <h2 className="text-2xl font-light mb-4">{report.title}</h2>}
            {report.summary && (
              <div className="p-4 rounded-lg border mb-6" style={{ background: "oklch(0.08 0.02 265 / 0.6)", borderColor: "oklch(0.20 0.05 265 / 0.5)" }}>
                <p className="text-xs uppercase tracking-widest mb-2" style={{ color: "oklch(0.55 0.02 265)" }}>Executive summary</p>
                <p className="text-sm">{report.summary}</p>
              </div>
            )}
            {report.content && <Streamdown>{report.content}</Streamdown>}
          </article>
        ) : (
          <p style={{ color: "oklch(0.55 0.02 265)" }}>Project shared in read-only mode. No specific report attached.</p>
        )}

        <footer className="mt-16 pt-6 border-t text-xs" style={{ borderColor: "oklch(0.18 0.05 265 / 0.5)", color: "oklch(0.45 0.02 265)" }}>
          Generated by Oracle. JSON view: <code className="font-mono">/api/public/share/{slug}</code>
        </footer>
      </main>
    </div>
  );
}
